#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source the AdditiveFOAM environment variables
. "${0%/*}/etc/bashrc" || exit 1

# Parse arguments for library/application compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments || exit 1

#------------------------------------------------------------------------------
# AdditiveFOAM build information

GIT_DESCRIBE=$(git describe --tags --always 2>/dev/null) \
    || GIT_DESCRIBE="undefined"

GIT_SHA1=$(git rev-parse HEAD 2>/dev/null) \
    || GIT_SHA1="undefined"

export ADDITIVEFOAM_BUILD_FLAGS="\
$ADDITIVEFOAM_BUILD_FLAGS \
-DADDITIVEFOAM_GIT_DESCRIBE=\\\"$GIT_DESCRIBE\\\" \
-DADDITIVEFOAM_GIT_SHA1=\\\"$GIT_SHA1\\\""

#------------------------------------------------------------------------------
# Compile AdditiveFOAM libraries and applications

applications/Allwmake $targetType $*

#------------------------------------------------------------------------------
