#!/bin/bash

cd ${0%/*} || exit 1

# Run AdditiveFOAM solver in parallel
decomposePar > log.decomposePar 2>&1
cores=$(foamDictionary -entry numberOfSubdomains -value system/decomposeParDict)
mpirun -np $cores --bind-to none additiveFoam -parallel > log.additiveFoam 2>&1

# Reconstruct ExaCA data into a single file
reconstructPar > log.reconstructPar 2>&1
echo "x,y,z,tm,ts,cr" > solidificationData.csv
cat ExaCA/* >> solidificationData.csv

# Clean up decomposed data if the output file exists and contains data
if [ -e solidificationData.csv ]; then
    if [ -n "$(find . solidificationData.csv -prune -size +100k)" ]; then
        rm -r ExaCA
        rm -r processor*
    fi
fi
