#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
application=`getApplication`

#------------------------------------------------------------------------------
# Case setup
runApplication blockMesh

runApplication createScanPath
#------------------------------------------------------------------------------
# AdditiveFOAM
runLayers \
    -nLayers 2 \
    -nCellsPerLayer 4 \
    -layerThickness 40e-6
#------------------------------------------------------------------------------
# Reconstruction
reconstructLayers

reconstructExaCAData

reconstructSolidificationData
#------------------------------------------------------------------------------
