#!/bin/bash
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     | Website:  https://openfoam.org
#   \\  /    A nd           | Copyright (C) 2011-2022 OpenFOAM Foundation
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     reconstructLayers
#
# Description
#     Reconstructs a multilayer simulation into the case directory
#------------------------------------------------------------------------------

baseDir=${PWD}
caseList=()
for layer in layer*
do
    caseList+=("$baseDir/$layer")
done
nLayers=${#caseList[@]}
echo "Found $nLayers parallel-in-time layers in $baseDir"

for (( layer=$(($nLayers-1)); layer>=0; layer-- ))
do
    reconstructPar -case "${caseList[$layer]}" -newTimes > log.reconstructPar_layer$layer
    timeList=( $(foamListTimes -case "${caseList[$layer]}" -withZero) )
    for time in "${timeList[@]:1}"
    do  
        cp -rn "${caseList[$layer]}/$time" "$baseDir"
        cp -rn "${caseList[$layer]}/constant/polyMesh" "$baseDir/$time"
    done
done

#------------------------------------------------------------------------------
