#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     | Website:  https://openfoam.org
#   \\  /    A nd           | Copyright (C) 2011-2025 OpenFOAM Foundation
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
#               Copyright (C) 2023-2026 Oak Ridge National Laboratory
#-------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# File
#     etc/bashrc
#
# Description
#     Startup file for AdditiveFOAM
#
#------------------------------------------------------------------------------

# AdditiveFOAM version
export ADDITIVEFOAM_VERSION=2.0.0-dev

# OpenFOAM version
export ADDITIVEFOAM_OPENFOAM_VERSION=13

if [ -z "${WM_PROJECT_DIR:-}" ]
then
    echo "OpenFOAM-$ADDITIVEFOAM_OPENFOAM_VERSION does not appear to be sourced." >&2
    return 1 2>/dev/null || exit 1
fi

if [ "${WM_PROJECT:-}" != "OpenFOAM" ] || \
   [ "${WM_PROJECT_VERSION:-}" != "$ADDITIVEFOAM_OPENFOAM_VERSION" ]
then
    echo "AdditiveFOAM requires OpenFOAM-$ADDITIVEFOAM_OPENFOAM_VERSION." >&2
    return 1 2>/dev/null || exit 1
fi


# AdditiveFOAM path
if [ -z "${ADDITIVEFOAM_PROJECT_DIR:-}" ]
then
    [ -n "${BASH:-}" ] && additivefoamBashrcFile=${BASH_SOURCE}
    [ -n "${ZSH_NAME:-}" ] && additivefoamBashrcFile=$0

    if [ -n "${additivefoamBashrcFile:-}" ]
    then
        export ADDITIVEFOAM_PROJECT_DIR=$(cd "$(dirname "$additivefoamBashrcFile")/.." && pwd -P)
    elif [ -e etc/bashrc ] && [ -d applications ]
    then
        export ADDITIVEFOAM_PROJECT_DIR=$(pwd -P)
    else
        export ADDITIVEFOAM_PROJECT_DIR=$HOME/AdditiveFOAM
    fi

    unset additivefoamBashrcFile
fi


# AdditiveFOAM bin directory for helper scripts
if [ -d "$ADDITIVEFOAM_PROJECT_DIR/bin" ]; then
    export PATH=$ADDITIVEFOAM_PROJECT_DIR/bin:$PATH
fi


# AdditiveFOAM directories
export ADDITIVEFOAM_TUTORIALS="$ADDITIVEFOAM_PROJECT_DIR/tutorials"
export ADDITIVEFOAM_APPLICATIONS="$ADDITIVEFOAM_PROJECT_DIR/applications"
export ADDITIVEFOAM_ETC="$ADDITIVEFOAM_PROJECT_DIR/etc"

export ADDITIVEFOAM_GLOBAL="$ADDITIVEFOAM_PROJECT_DIR/src/AdditiveFOAM/global"

# AdditiveFOAM build flags
export ADDITIVEFOAM_BUILD_FLAGS="\
-I$ADDITIVEFOAM_GLOBAL \
-DADDITIVEFOAM_VERSION=\\\"$ADDITIVEFOAM_VERSION\\\""

#------------------------------------------------------------------------------
