#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
application=`getApplication`

#------------------------------------------------------------------------------
# Case setup
runApplication blockMesh

runApplication decomposePar
#------------------------------------------------------------------------------
# AdditiveFOAM
runParallel $application
#------------------------------------------------------------------------------
# Reconstruction
runApplication reconstructPar

reconstructExaCAData

reconstructSolidificationData
#------------------------------------------------------------------------------
