title: AdditiveFOAM Documentation
description: Documentation for the AdditiveFOAM project.
baseurl: "/AdditiveFOAM"
url: "https://ORNL.github.io"
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
