#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Build libraries and solver
wmake $targetType utilities
wmake $targetType functionObjects
wmake $targetType movingHeatSource
wmake $targetType

#------------------------------------------------------------------------------
