#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------
# Generate header for git information
HEADER_FILE="${0%/*}/Make/gitInfo.H"
GIT_DESCRIBE=$(git describe --tags --always 2>/dev/null) || GIT_DESCRIBE="undefined"
GIT_SHA1=$(git rev-parse HEAD 2>/dev/null) || GIT_SHA1="undefined"

cat > "$HEADER_FILE" << EOF
#ifndef gitInfo_H
#define gitInfo_H

// Git describe
#define ADDITIVEFOAM_GIT_DESCRIBE "$GIT_DESCRIBE"

// Git hash
#define ADDITIVEFOAM_GIT_SHA1 "$GIT_SHA1"

#endif
EOF

export ADDITIVEFOAM_BUILD_FLAGS="-DGIT_MODULE_ENABLED=1"

#------------------------------------------------------------------------------
# Build libraries and solver
wmake $targetType functionObjects
wmake $targetType movingHeatSource
wmake $targetType

#------------------------------------------------------------------------------
